### ISSUE TITLE
Error while generating the project with --generate-example

### ISSUE THREAD

**Issue by nonotest** [brodybits/create-react-native-module#312]
Hello, haven't found any existing issue with this.

If running
```
create-react-native-module --generate-example
```

The cli tries to pull `react-native@react-native@latest`

Managed to make it work by specifying the version

```
create-react-native-module --generate-example --example-react-native-version 0.62
```

```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 6.21 GB / 32.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by brodybits** [comment]
> If running
> 
> ```
> create-react-native-module --generate-example
> ```

Unfortunately that means nothing to me since this CLI will fail with an error message if no name is given.

I do need the full command line and which `create-react-native-module` version (do `create-react-native-module --version`) to investigate this further.

I did also notice macOS 10.14 & Node.js version 13 in the system information. I generally test on macOS 10.15 and Node.js 12, may start testing on Node.js 14 in the near future.

My apologies for the delay.

**Comment by brodybits** [comment]
My comment may have been a little on the rude side, my apologies.

I took another look at the posted system info, and realized it seems to be using a "fish" shell which I have never tried. (I do not even know what tool outputs the posted system info.)

I am especially baffled since this tool really needs the module name to work, which I do not see in the description.

I think it would be really helpful to post both the output of `create-react-native-module --version` and some of the output from running this tool to help understand what options it is running with.

Thanks!

**Comment by nonotest** [comment]
Hello,

no worries, no ofense taken at all.

yep I am using `Fish` shell but seeing as there are a few :+1: it might affect people on another shell.

```
create-react-native-module --version                                                                                                                                      Thu Apr 30 13:04:41 2020
0.18.1-dev
```

```
create-react-native-module --generate-example

...
✖ Downloading template
error Error: Command failed: yarn add react-native@react-native@latest
error Couldn't find any versions for "react-native" that matches "react-native@latest"
yarn add v1.21.1
info No lockfile found.
```

I remember seeing a change with the template options of react-native cli a while back. It could be related ?

**Comment by brodybits** [comment]
Thanks. It would actually help if you could show a couple more things:

- the beginning of the output, where it shows all of the options that it is generating with
- how did you install the react-native CLI?

I generally just do `npm install -g react-native-cli` to install the react-native CLI, don't recall seeing this kind of problem with it.

**Comment by brodybits** [comment]
I really need some more information before I can do anything to resolve this issue:

- the full console output
- how you installed the react-native CLI tool

I would like to make a new release in the next few days. Thanks.

**Comment by AaronLeoCooper** [comment]
Hi @brodybits, I'm also facing this same issue, whereby it attempts to add react-native of version: `react-native@react-native@latest` when running the CLI tool with `--generate-example`.

I'm running inside zsh shell on macOS, Yarn v1.19.1, using the latest version of `create-react-native-module`. Installed it today globally with yarn and running it using the instructions included in the official React Native docs page here: https://reactnative.dev/docs/native-modules-setup. I also have the latest version of `react-native` installed globally via yarn (CLI version 4.8.0).

Sorry but I can't share my complete log for this issue, except for the error:

```
✖ Downloading template
error Error: Command failed: yarn add react-native@react-native@latest
error Couldn't find any versions for "react-native" that matches "react-native@latest"
```

Using `--example-react-native-version` as suggested by the OP worked for me.

**Comment by brodybits** [comment]
> I also have the latest version of `react-native` installed globally
> [...]

I generally do `npm install -g react-native-cli`, according to my understanding of the React Native documentation from last year. They seem to have changed it to recommend just using `npx react-native ...`, which would imply `npm install -g react-native` (or the equivalent on Yarn). I am now suspecting that this difference could explain the difference in observed behavior between myself and some others.

I am now thinking to add & use `@react-native-community/cli` as a dependency, as suggested in #204, in order to resolve this issue for good. It seems to be a very heavy dependency but maybe worth it.

I hope to investigate and resolve this issue in the next couple of weeks or so, unfortunately fighting some urgent deadlines right now.

**Comment by brodybits** [comment]
This is now confirmed as a bug. Using [https://github.com/jasongin/nvs](nvs) to switch between global Node.js installations, which is highly recommended due to its portable nature, I have tried the following in my work area:

**1: `npm i -g react-native`**

Does give me some unfortunate output from the obsolete core-js@2 version, which is off-topic.

At this point, `react-native --version` shows: `4.9.0`

`./bin/cli.js --generate-example adamTest1` with no `--example-react-native-version` gave me some slightly colorful output including this error message:

```
✖ Downloading template
error Error: Command failed: yarn add react-native@react-native@latest
error Couldn't find any versions for "react-native" that matches "react-native@latest"
```

and then continued until the following error output:

```
check for valid pod version in ./react-native-adam-test1/example/ios
pod --version failure, aborting with broken example app
Error while creating library module react-native-adam-test1
Error: Command failed with ENOENT: pod --version
spawnSync pod ENOENT
```

`ls react-native-adam-test1/example` shows just 2 files at this point:

```
App.js		metro.config.js
```

The following command worked correctly and gave me a module with a working example:

```
./bin/cli.js --generate-example --example-react-native-version 0.62 adamTest2
```

**2: `npm i -g react-native-cli`**

`react-native --version` gave the following output:

```
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```

In this case, using `--generate-example` continues to work for me like before.

As I said before:

> I am now thinking to add & use `@react-native-community/cli` as a dependency, as suggested in #204, in order to resolve this issue for good. It seems to be a very heavy dependency but maybe worth it.

I will likely test it with `npm i -g react-native`, `npm i -g react-native-cli`, and with no external react-native CLI installed.
